name: validate

on:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.11.6
      - name: Format check
        run: tofu fmt -check -recursive
      - name: Validate
        run: tofu init -backend=false && tofu validate
